apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitor-argocd-sa
  namespace: default
  labels:
    app: monitor-argocd
    chart: monitor-argocd
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}