apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitor-argocd
  namespace: poc
spec:
  project: default
  source:
    repoURL: https://github.com/JaimeHenaoChallange/monitor-argocd-cronjob.git
    targetRevision: main
    path: charts/monitor-argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: poc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true